### ISSUE TITLE
Input value is not being displayed correctly

### ISSUE THREAD

**Issue by sdattatri** [marcocesarato/react-native-input-spinner#14]
I just updated my project and suddenly the input initial value is no longer displayed correctly. It is showing only zero.
The relevant piece of code is:
<View style={styles.repeatCount}>
            <Text style={styles.rText}>{`Text size (${fontSize})`}</Text>
            <InputSpinner
              style={styles.rInput}
              value={fontSize}
              min={18}
              max={48}
              step={2}
              rounded={false}
              showBorder={true}
              width={120}
              height={35}
              editable={false}
              colorLeft="#6a51ae"
              colorRight="#6a51ae"
              onChange={(value) => {
                setFontSize(value);
              }}
            />
          </View>
Once I click on plus or minus the input display is initialized and after that I am able to modify it. But when I come back to the screen again, it just shows zero.  The fontSize variable has the correct value as displayed as part of the label(for test purposes).

There are no relevant errors or warnings.

**Comment by marcocesarato** [comment]
Hi, thanks for your issue. 
This issue has now been fixed in the new release v1.3.0

**Comment by sdattatri** [comment]
Hi,
Thanks for the prompt response.  I am still having problems with this.  Clicking on the minus just toggles between the max value and the one below it.  It still does not display the value correctly.
